"use strict";
const state = {shares:100,calls:2,version:12,ideaVersion:null,paused:false,eventId:1044,rules:[{name:"Large stock print",asset:"Stock",min:1000000,enabled:true},{name:"Large option premium",asset:"Option",min:100000,enabled:true},{name:"Repeated large prints",asset:"Mixed",min:3000000,enabled:true}],history:[{title:"Design preview opened",detail:"All values are synthetic. No integrations are connected.",time:"10:31:00"}]};
const $ = id => document.getElementById(id);
const money = n => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const escapeHtml = text => String(text).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let toastTimer;
function notify(text){$("toast").textContent=text;$("toast").classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>$("toast").classList.add("hidden"),4000);}
function go(page){document.querySelectorAll(".page").forEach(el=>el.classList.toggle("hidden",el.id!=="page-"+page));document.querySelectorAll(".nav").forEach(el=>{el.classList.toggle("active",el.dataset.page===page);el.setAttribute("aria-current",el.dataset.page===page?"page":"false");});if(page==="history")renderHistory();window.scrollTo(0,0);}
document.querySelectorAll("[data-page]").forEach(el=>el.addEventListener("click",()=>go(el.dataset.page)));
document.querySelectorAll("[data-go]").forEach(el=>el.addEventListener("click",()=>go(el.dataset.go)));
document.querySelector(".brand").addEventListener("click",event=>{event.preventDefault();go("overview");});
function record(title,detail){state.history.unshift({title,detail,time:new Date().toLocaleTimeString("en-US",{hour12:false})});renderHistory();}
function renderHistory(){$("history-list").innerHTML=state.history.map(item=>'<div class="history-item"><time>'+escapeHtml(item.time)+'</time><div><strong>'+escapeHtml(item.title)+'</strong><p>'+escapeHtml(item.detail)+'</p></div></div>').join("");}
function renderRules(){$("rule-count").textContent=state.rules.length;$("enabled-count").textContent=state.rules.filter(rule=>rule.enabled).length;$("rules-body").innerHTML=state.rules.map((rule,i)=>'<tr><td><strong>'+escapeHtml(rule.name)+'</strong><small>NVDA · demo rule v1</small></td><td>'+escapeHtml(rule.asset)+'</td><td>'+money(rule.min)+'</td><td>60s</td><td><span class="pill">'+(rule.enabled?"ENABLED":"PAUSED")+'</span></td><td><button data-toggle="'+i+'">'+(rule.enabled?"Pause":"Enable")+'</button></td></tr>').join("");$("rules-body").querySelectorAll("[data-toggle]").forEach(button=>button.addEventListener("click",()=>{const rule=state.rules[Number(button.dataset.toggle)];rule.enabled=!rule.enabled;record("Rule "+(rule.enabled?"enabled":"paused"),rule.name+" — preview only.");renderRules();}));}
function flowItem(option=false,id=1042){return '<div class="flow-item"><div class="flow-top"><div class="symbol-icon '+(option?"purple":"")+'">N</div><div><strong>NVDA'+(option?' <span class="pill">OPTION</span>':'')+'</strong><small>'+(option?"Sep 18, 2026 · 155 CALL":"Stock · held underlying")+'</small></div><div class="amount">'+(option?"$130,000":"$12,000,000")+'<small>'+(option?"TOTAL PREMIUM":"TRADE NOTIONAL")+'</small></div></div><div class="flow-description">'+(option?"250 contracts × $5.20 × 100":"80,000 shares × $150.00")+' <span class="muted">· aggressor unknown</span></div><div class="flow-meta"><span class="pill '+(option?"amber":"")+'">'+(option?"POLLED · DEMO":"STREAM · DEMO")+'</span><span>'+(option?"Observed 8s later":"Observed 0.6s later")+'</span><span>WR-'+id+'</span><button class="inspect">Review impact →</button></div></div>';}
function bindFlow(){$("flow-list").querySelectorAll(".inspect").forEach(el=>el.addEventListener("click",()=>go("suggestions")));}
$("flow-list").innerHTML=flowItem(false,1042)+flowItem(true,1043);bindFlow();
$("simulate").addEventListener("click",()=>{if(state.paused)return notify("Resume the demo feed to simulate another print.");const id=state.eventId++;$("flow-list").insertAdjacentHTML("afterbegin",flowItem(id%2===0,id));while($("flow-list").children.length>5)$("flow-list").lastElementChild.remove();bindFlow();record("Synthetic print observed","WR-"+id+" added locally. No Telegram message sent.");notify("Synthetic print added. Nothing was sent externally.");});
$("pause").addEventListener("click",()=>{state.paused=!state.paused;$("pause").textContent=state.paused?"Resume demo feed":"Pause demo feed";record("Demo feed "+(state.paused?"paused":"resumed"),"This control changes preview behavior only.");});
$("new-rule").addEventListener("click",()=>$("rule-dialog").showModal());
$("close-dialog").addEventListener("click",()=>$("rule-dialog").close());
$("rule-form").addEventListener("submit",event=>{event.preventDefault();const name=$("rule-name").value.trim();const min=Number($("rule-min").value);if(!name||!Number.isFinite(min)||min<=0||min>1000000000)return notify("Enter a rule name and a valid positive amount.");state.rules.push({name,asset:$("rule-asset").value,min,enabled:true});renderRules();$("rule-dialog").close();$("rule-form").reset();record("Demo rule created",name+" — not connected to live data.");notify("Demo rule saved for this preview session.");});
function exposure(){return (state.shares+state.calls*100*.55)*150;}
function renderPositions(){const total=exposure();$("delta-total").textContent=money(total);$("snapshot-label").textContent="snapshot v"+state.version;$("exposure-percent").innerHTML=(total/1000).toFixed(1)+'%<small>NVDA delta / illustrative equity</small>';$("exposure-fill").style.width=Math.min(100,Math.max(0,total/1000))+"%";document.querySelector(".exposure>p").innerHTML=state.shares+" shares + "+state.calls+" long calls.<br>Long calls add directional exposure.";$("positions-subtitle").textContent="Demo account · reviewed snapshot v"+state.version+" · illustrative prices";$("positions-body").innerHTML='<tr><td><strong>NVDA</strong><small>Stock</small></td><td>+'+state.shares+' shares</td><td>$150.00</td><td>1.00</td><td>'+money(state.shares*150)+'</td><td>Reviewed demo</td></tr><tr><td><strong>NVDA 155 CALL</strong><small>2026-09-18 · standard multiplier 100</small></td><td>+2 contracts</td><td>$5.20</td><td>0.55</td><td>$16,500</td><td>Reviewed demo</td></tr>';if(state.ideaVersion!==null&&state.ideaVersion!==state.version){$("idea-state").textContent="EXPIRED · POSITIONS CHANGED";$("idea-state").classList.add("amber");$("suggestion-content").querySelectorAll("button").forEach(button=>button.disabled=true);}}
function renderDiff(){const next=Number($("ocr-shares").value);$("ocr-diff").textContent="NVDA shares: "+state.shares+" → "+(Number.isFinite(next)?next:"?")+". Calls remain +2. Unshown holdings remain unchanged.";}
$("load-ocr").addEventListener("click",()=>{$("ocr-review").classList.remove("hidden");$("ocr-shares").value="150";$("ocr-confirm").checked=false;renderDiff();$("ocr-review").scrollIntoView({behavior:"smooth",block:"start"});});
$("ocr-shares").addEventListener("input",renderDiff);
$("ocr-form").addEventListener("submit",event=>{event.preventDefault();const next=Number($("ocr-shares").value);if(!Number.isInteger(next)||next<0||next>100000||!$("ocr-confirm").checked)return notify("Review the quantity and confirm the changes.");const before=state.shares;state.shares=next;state.version++;renderPositions();$("ocr-review").classList.add("hidden");record("Demo position snapshot committed","v"+state.version+": NVDA "+before+" → "+next+" shares. Prior suggestions expired.");notify("Snapshot v"+state.version+" committed. Prior ideas require recalculation.");});
$("generate").addEventListener("click",()=>{state.ideaVersion=state.version;$("idea-state").textContent="DEMO SNAPSHOT v"+state.version;$("idea-state").classList.remove("amber");const current=exposure();const trim=Math.min(50,state.shares);const candidates=[{tag:"WAIT FOR CONFIRMATION",title:"Hold & observe",amount:current,cost:"$0 incremental debit",detail:"The large print's intent is unknown. Wait for price confirmation; existing exposure remains.",condition:"Revisit if price or position inputs change."},{tag:"REDUCE EXPOSURE",title:"Trim "+trim+" shares",amount:current-trim*150,cost:money(trim*150)+" illustrative proceeds",detail:"Reduce held shares without adding an option leg. Sale proceeds are not profit.",condition:"Verify closable quantity and current bid before review."},{tag:"EXPLORE PROTECTION",title:"Buy 1 protective put",amount:current-4500,cost:"$200 illustrative premium + costs",detail:"Example: standard 145 put with delta −0.30 at $2.00. Premium is incremental risk, not total portfolio loss.",condition:"Verify expiry, live ask, cash and protection objective."}];$("suggestion-content").innerHTML='<div class="notice">Illustrative delta now '+money(current)+'. Objective: '+escapeHtml($("objective").value)+'. All prices and Greeks below are synthetic assumptions.</div><div class="idea-grid">'+candidates.map(candidate=>'<article class="panel idea"><span class="pill">'+candidate.tag+'</span><h2>'+candidate.title+'</h2><p>'+candidate.detail+'</p><div class="idea-amount">'+money(candidate.amount)+'</div><p>Delta dollars after · local approximation</p><div class="setting-line"><b>Cost / proceeds</b><span>'+candidate.cost+'</span></div><div class="setting-line"><b>Review condition</b><span>'+candidate.condition+'</span></div><button class="full save-idea">Save demo idea</button></article>').join("")+'</div>';$("suggestion-content").querySelectorAll(".save-idea").forEach((button,i)=>button.addEventListener("click",()=>{record("Demo idea saved",candidates[i].title+" — manual review only, no order submitted.");notify("Idea saved to preview history. No trade placed.");}));record("Demo alternatives generated","Based on synthetic snapshot v"+state.version+". No AI model called.");});
$("objective").addEventListener("change",()=>{if(state.ideaVersion!==null){$("idea-state").textContent="RECALCULATE · OBJECTIVE CHANGED";$("idea-state").classList.add("amber");$("suggestion-content").querySelectorAll("button").forEach(button=>button.disabled=true);}});
renderRules();renderPositions();renderHistory();
